#!/bin/bash

echo "╔════════════════════════════════════════════════════════════╗"
echo "║         Rubik's Cube Solver - Launcher                    ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Check if running in Eclipse
if [ -d "bin" ] && [ "$(ls -A bin 2>/dev/null)" ]; then
    echo "✓ Compiled classes found in bin/"
else
    echo "⚠ No compiled classes found."
    echo ""
    echo "This project requires Eclipse IDE to run because:"
    echo "  1. OpenCV native libraries need to be configured"
    echo "  2. GUI requires display environment"
    echo "  3. Webcam access needs proper permissions"
    echo ""
    echo "📋 TO RUN THIS PROJECT:"
    echo ""
    echo "1. Open Eclipse IDE"
    echo "2. Import this project (File → Import → Existing Projects)"
    echo "3. Ensure OpenCV library is configured:"
    echo "   - Window → Preferences → Java → User Libraries"
    echo "   - Should see 'opencv-4.0.0' library"
    echo "4. Right-click src/MainFrame.java"
    echo "5. Select 'Run As' → 'Java Application'"
    echo ""
    echo "📹 WHAT WILL HAPPEN:"
    echo "  - Two windows will open"
    echo "  - Camera window: Shows live webcam feed"
    echo "  - Display window: Shows cube state and solution"
    echo ""
    echo "⌨️  CONTROLS:"
    echo "  - SPACE: Capture cube face"
    echo "  - R: Reset"
    echo "  - X: Exit"
    echo ""
    echo "📖 For detailed instructions, see:"
    echo "  - QUICKSTART.md"
    echo "  - PROJECT_OVERVIEW.md"
    echo ""
    exit 1
fi

echo "✓ Java found: $(java -version 2>&1 | head -n 1)"
echo ""
echo "⚠ This application requires:"
echo "  1. OpenCV libraries (configured in Eclipse)"
echo "  2. Webcam access"
echo "  3. GUI display"
echo ""
echo "Please run through Eclipse IDE for best results."
echo ""
echo "See QUICKSTART.md for instructions."
